FINAL = graviton-gui
OBJS = 	main.o font.o frame.o frame-pp.o frame-ot.o gfx.o input.o console.o osd.o spawn.o tool.o command.o fps.o

CFLAGS = -O4 -Wall `sdl-config --cflags` -msse
LFLAGS = -lGL -lGLU -lSDL_image -lSDL_ttf `sdl-config --libs`

all: final

final: $(OBJS)
	@echo gcc $(LFLAGS) $(OBJS) -o$(FINAL)
	@gcc $(LFLAGS) $(OBJS) -o$(FINAL)

clean:
	rm -rf *.o $(FINAL)

(%.o): %.c
	@echo gcc -c $(CFLAGS) $(subst ,, $*.c) -o$*.o
	@gcc -c $(CFLAGS) $(subst ,, $*.c) -o$*.o
