FINAL = graviton-console
OBJS = 	main.o frame.o frame-pp.o frame-ot.o spawn.o tool.o command.o console.o input.o fps.o

CFLAGS = -O4 -Wall -msse -DNO_GUI
LFLAGS = -lm -lpthread

all: final

final: $(OBJS)
	@echo gcc $(LFLAGS) $(OBJS) -o$(FINAL)
	@gcc $(LFLAGS) $(OBJS) -o$(FINAL)

clean:
	rm -rf *.o $(FINAL)

(%.o): %.c
	@echo gcc -c $(CFLAGS) $(subst ,, $*.c) -o$*.o
	@gcc -c $(CFLAGS) $(subst ,, $*.c) -o$*.o
